# 请输入自己的appid和appsecret
oauth: 
  wx:
    miniapp:
      open: true
      appId: appId
      appSecret: appSecret
      url: https://api.weixin.qq.com/sns/jscode2session
    pub:
      open: true
      appId: appId
      appSecret: appSecret
      url: https://api.weixin.qq.com/sns/oauth2/access_token

  phone:
    dysms:
      appId: appId
      appSecret: appSecret
